version: "3.8"

services:
  app:
    build: .
    container_name: dealer-bot
    restart: always
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - laravel_network
    depends_on:
      - db
    env_file:
      - .env # Laravel .env faylini yuklash

  db:
    image: postgres:15
    container_name: dealer_bot_db
    restart: always
    ports:
      - "5432:5432"
    networks:
      - laravel_network
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env # PostgreSQL .env faylidan o‘zgaruvchilarni oladi
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  nginx:
    image: nginx:alpine
    container_name: dealer_bot_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel_network
    depends_on:
      - app

networks:
  laravel_network:
    driver: bridge

volumes:
  pgdata:
